Exercises 1.i and 1.ii
univas/html-exercises pull request #10
Opened 2017-03-03 00:24 UTC by danielSLopes

Esses são meus exercícios 1.i e 1.ii.

2017-03-06 23:44 UTC, edysegura requested changes
Olá @danielSLopes!

Segue a correção do seu exercício. Qualquer dúvida estou a disposição.

Abraços,

2017-03-06 23:44 UTC, edysegura commented on daniel-lopes/1.i/README.md
> +**Obs.**: Ao criar a página lembre-se de considerar o valor semântico de cada *tag* para o conteúdo a ser marcado.
Não precisava copiar esse arquivo novamente!

2017-03-06 23:44 UTC, edysegura commented on daniel-lopes/1.i/daniel-simoes.html
> +<html lang="en">
Como o conteúdo está em português alterar o atributo `lang="en"` para `lang="pt-br"`

2017-03-06 23:44 UTC, edysegura commented on daniel-lopes/1.i/daniel-simoes.html
> +    <li>Aline Heloisa Silva Villela</li>
Faltou a tag pai do `<li>` que pode ser `<ol>` ou `<li>`

2017-03-06 23:44 UTC, edysegura commented on daniel-lopes/1.i/daniel-simoes.html
> +
Qual o motivo desta linha em branco?

2017-03-06 23:44 UTC, edysegura commented on daniel-lopes/1.i/daniel-simoes.html
> +
E das debaixo do parágrafo também?

2017-03-06 23:44 UTC, edysegura commented on daniel-lopes/1.ii/README.md
> +Obs.: Lembre-se de considerar o valor semântico de cada tag para o conteúdo a ser marcado.
Não precisava copiar esse arquivo também!

2017-03-06 23:44 UTC, edysegura commented on daniel-lopes/1.ii/curriculo-daniel.html
> +<html lang="en">
Qual idioma está o currículo?

2017-03-06 23:44 UTC, edysegura commented on daniel-lopes/1.ii/curriculo-daniel.html
> +<body background="http://www.shximai.com/data/out/101/67461508-imac-wallpapers.jpg" bgproperties="fixed">
Não utilizar atributos de formatação no HTML. O propósito do HTML é de estrutura e dar semântica a informação, para estilizar o HTML utilize o CSS.

`background="http://www.shximai.com/data/out/101/67461508-imac-wallpapers.jpg" bgproperties="fixed"`

2017-03-06 23:44 UTC, edysegura commented on daniel-lopes/1.ii/curriculo-daniel.html
> +<body background="http://www.shximai.com/data/out/101/67461508-imac-wallpapers.jpg" bgproperties="fixed">
Para mais informações leia [este artigo](http://maujor.com/tutorial/intrtut.php).

2017-03-06 23:44 UTC, edysegura commented on daniel-lopes/1.ii/curriculo-daniel.html
> +        <img width="200px" height="200px" src="https://scontent.fgig1-3.fna.fbcdn.net/v/t1.0-9/15420787_959437627493481_2101306811562930277_n.jpg?oh=236564e4b3a5ce8fcfd3b1ee2e56041f&oe=593626E8"
Não utilizar os atributos `width="200px" height="200px"` pois isso inviabiliza um layout responsivo futuramente. Via CSS é possível fazer a mesma coisa!

2017-03-06 23:44 UTC, edysegura commented on daniel-lopes/1.ii/curriculo-daniel.html
> +            <font color=white>
Não utilizar elementos duplicados no HTML e nem atributos de formatação. Exemplos de alguns [elementos obsoletos](https://www.tutorialspoint.com/html/html_deprecated_tags.htm).

2017-03-06 23:44 UTC, edysegura commented on daniel-lopes/1.ii/curriculo-daniel.html
> +                <li>Ensino Médio Completo</li>
Está faltando a tag `<ul></ul>` ou `<ol></ol>`

2017-03-06 23:44 UTC, edysegura commented on daniel-lopes/1.ii/curriculo-daniel.html
> +                <li>1 ano como atendente em Lanchonete Vinícius</li>
Está faltando a tag `<ul></ul>` ou `<ol></ol>`

2017-03-06 23:44 UTC, edysegura commented on daniel-lopes/1.ii/curriculo-daniel.html
> +                <li>Inglês Intermediário</li>
Está faltando a tag `<ul></ul>` ou `<ol></ol>`

2017-03-06 23:44 UTC, edysegura commented on daniel-lopes/1.ii/curriculo-daniel.html
> +    <center>
Onde você encontrou essa tag??

2017-03-07 04:33 UTC, danielSLopes commented on daniel-lopes/1.ii/README.md
> +Obs.: Lembre-se de considerar o valor semântico de cada tag para o conteúdo a ser marcado.
No meu código essas linhas não aparecem, não entendi o porque.

2017-03-09 02:33 UTC, edysegura approved these changes
Awesome!!

2017-03-09 02:41 UTC, merged