Samuel
univas/html-exercises pull request #18
Opened 2017-03-10 01:28 UTC by cem10000

estou enviando os exercícios para correção

2017-03-22 01:17 UTC, edysegura commented
Olá @cem10000 !

Não se esqueça de colocar uma foto no seu perfil!

![image](https://cloud.githubusercontent.com/assets/5324414/24177897/31a5c72c-0e84-11e7-9828-bf14a1def440.png)

2017-03-22 01:20 UTC, edysegura requested changes
Olá @cem10000 !

Lembre-se sempre de formatar o HTML para melhorar a leitura e manutenção do arquivo!

As tags `<li>` devem sempre ser inseridas dentro da tag `<ul>` ou `<ol>`

Abraços,

2017-03-22 01:20 UTC, edysegura commented on samuel/1.i/index.html
> +    <li>Valéria Santos Paduan Silva<li/>
As tags `<li>` devem sempre ser inseridas dentro da tag `<ul>` ou `<ol>`

2017-03-23 23:05 UTC, cem10000 commented
edysegura edy fiz as estraçoes pedidas

2017-03-27 00:32 UTC, edysegura reviewed
Olá @cem10000 !

Lembre-se de formatar o seu HTML para ficar legível e para facilitar a manutenção.

Abraços,

2017-03-27 00:32 UTC, edysegura commented on samuel/1.ii/index.html
> +<title>Curriculo</title>
Adicione o seu nome ao `<title>` também!

2017-04-26 02:49 UTC, edysegura approved these changes

2017-04-26 02:49 UTC, merged