Exercicio 1.i
univas/html-exercises pull request #3
Opened 2017-02-26 03:07 UTC by frcleiton

Exercício 1.i

2017-03-02 02:43 UTC, edysegura reviewed
Hi @frcleiton! 

Very well done! I have only few question for you!

2017-03-02 02:43 UTC, edysegura commented on cleiton-ferreira/1.i/index.html
> +        <p>Para mais informações ou dúvidas entre em contato.</p>
@frcleiton This paragraph is with misaligned indentation, don't you think?

2017-03-02 02:43 UTC, edysegura commented on cleiton-ferreira/1.i/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1">
Why did you use this tag? Are you preparing it for mobile device as well?

2017-03-02 19:08 UTC, frcleiton commented on cleiton-ferreira/1.i/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1">
Hi Edy, yes.

2017-03-02 19:09 UTC, frcleiton commented on cleiton-ferreira/1.i/index.html
> +        <p>Para mais informações ou dúvidas entre em contato.</p>
I agree

2017-03-07 02:43 UTC, edysegura requested changes
Hi @frcleiton!

Please take a look in my comments and let me know if you have doubts.

Cheers

2017-03-07 02:43 UTC, edysegura commented on cleiton-ferreira/1.ii/index.html
> +<html lang="en">
The content of this page is in English or in Portuguese?? How about change it to `lang="pt-br"`

2017-03-07 02:43 UTC, edysegura commented on cleiton-ferreira/1.i/index.html
> +<html lang="en">
The content of this page is in English or in Portuguese?? How about change it to `lang="pt-br"`

2017-03-07 02:43 UTC, edysegura commented on cleiton-ferreira/1.ii/index.html
> +    <table align="center">
Please don't use this attribute anymore `align="center"` it breaks the meaning of HTML. You can do the same with CSS.

2017-03-07 02:43 UTC, edysegura commented on cleiton-ferreira/1.ii/index.html
> +            <th><img src="cleiton.jpg" alt="Cleiton" title="Foto" width="150" height="150" /></th>
Avoid to use these attributes `width="150" height="150"`

2017-03-07 02:43 UTC, edysegura commented on cleiton-ferreira/1.ii/index.html
> +            <th align="right"><h2>Curriculum Vitae</h2></th>
Same here `align="right"`

2017-03-07 02:43 UTC, edysegura commented on cleiton-ferreira/1.ii/index.html
> +                <p><h3>Cleiton Rezende Ferreira<h3></p>
It is not right to use `<h3>` inside a `<p>`

2017-03-07 02:43 UTC, edysegura commented on cleiton-ferreira/1.ii/index.html
> +    <p></p>
Why this empty `<p>`

2017-03-07 02:43 UTC, edysegura commented on cleiton-ferreira/1.ii/index.html
> +    <p></p>
There are more empty `<p>` below!

2017-03-09 22:49 UTC, frcleiton commented on cleiton-ferreira/1.ii/index.html
> +<html lang="en">
Done

2017-03-09 22:50 UTC, frcleiton commented on cleiton-ferreira/1.ii/index.html
> +    <table align="center">
done

2017-03-09 22:55 UTC, frcleiton commented on cleiton-ferreira/1.i/index.html
> +<html lang="en">
Hi Teacher, thanks for your comments and support.

2017-03-09 23:04 UTC, frcleiton commented
The index.html has been fixed.

2017-03-22 01:49 UTC, edysegura reviewed
Good job!! 👍

2017-03-22 01:49 UTC, edysegura approved these changes

2017-03-22 01:49 UTC, merged