htmlzao
univas/html-exercises pull request #6
Opened 2017-03-02 20:39 UTC by DJBZOMBIE

2017-03-09 02:44 UTC, edysegura commented
Olá @DJBZOMBIE !

O nome do diretório com o seu nome deveria ser  "daniel-julio-bernardo" ao invés de " Daniel Julio Bernardo"

2017-03-09 02:55 UTC, edysegura requested changes
Olá @DJBZOMBIE !

Seguem as minhas recomendações e em caso de dúvida é só me retornar!

Abraços,

2017-03-09 02:55 UTC, edysegura commented on Daniel Julio Bernardo/Exercicio 1/index.html
> +<html lang="en">
Como o conteúdo da página está em português o valor correto para o atributo é `lang="pt-br"`

2017-03-09 02:55 UTC, edysegura commented on Daniel Julio Bernardo/Exercicio 1/index.html
> +    <p> Valéria Santos Paduan Silva</p>
O ideal para exibir os nomes acima seria o uso de listas:

```html
<ul>
  <li>Aline Heloisa Silva Villela</li>
  <li>André Luiz Martins de Oliveira</li>
  .
  .
  .
</ul>
```

2017-03-09 02:55 UTC, edysegura commented on Daniel Julio Bernardo/Exercicio 2/index2.html
> +<html lang="en">
`lang="pt-br"`

2017-03-09 02:55 UTC, edysegura commented on Daniel Julio Bernardo/Exercicio 2/index2.html
> +
Não é recomendado o uso do elemento `<b>`. Use `<strong>` no lugar devido ao seu valor semântico e não pela formatação

2017-03-09 20:21 UTC, DJBZOMBIE commented on Daniel Julio Bernardo/Exercicio 2/index2.html
> +
E aí. 
Já concertei todos os erros do código, quanto ao nome do diretório... não cometerei o mesmo erro novamente.

2017-03-09 23:25 UTC, DJBZOMBIE commented
adicionei o repositório htmlzao2 e nele o nome do projeto esta conforme as regras

2017-03-22 01:39 UTC, edysegura reviewed
Faltou você formatar o seu HTML para melhorar a leitura e manutenção dos mesmo!

2017-03-27 00:44 UTC, edysegura commented on daniel-julio-bernardo/1.ii/index.html
> +    <p> Fui técnico de em fulanes na empresa beltrano informática</br>
O uso do `</br>` está errado!

2017-03-27 03:16 UTC, DJBZOMBIE commented
Okay chief! And now... finally is right ? lol

2017-03-30 20:57 UTC, DJBZOMBIE commented
I added Exercise 3(1.iii) in the same pull

2017-04-02 18:38 UTC, merged

2017-04-02 18:38 UTC, edysegura commented
Good job @DJBZOMBIE !!!