Todos Exercícios
univas/html-exercises pull request #7
Opened 2017-03-02 22:58 UTC by Brunna10

2017-03-07 03:23 UTC, edysegura reviewed
Oi @Brunna10 !

Veja os meus comentários e caso tenha dúvidas é só me retornar!

Abraços,

2017-03-07 03:23 UTC, edysegura commented on brunna-de-souza/1.i/index.html
> +<! DOCTYPE>
Está faltando o html no doctype acima! Ele deve ficar assim `<!DOCTYPE html>`

2017-03-07 03:23 UTC, edysegura commented on brunna-de-souza/1.i/index.html
> +<h3> Corpo Docente </h3>
Aqui o recomendado é usar o `<h2>` já que _corpo docente_ não é um subtítulo de _atuação profissional_.

2017-03-07 03:23 UTC, edysegura commented on brunna-de-souza/1.i/index.html
> +</p>
O recomendado acima é usar elementos para uma lista conforme abaixo:
```html
<ul>
  <li>Aline Heloisa Silva Villela</li>
  <li>André Luiz Martins de Oliveira</li>
  .
  .
  .
</ul>
```

2017-03-07 03:23 UTC, edysegura commented on brunna-de-souza/1.i/index.html
> +<h4> Informações </h4>
Aqui também o recomendado seria a utilização de um `h2`!

2017-03-07 03:23 UTC, edysegura commented on brunna-de-souza/1.ii/index.html
> +<!DOCTYPE>
Kd o html do seu doctype?

2017-03-07 03:23 UTC, edysegura commented on brunna-de-souza/1.ii/index.html
> +<h3> FORMAÇÃO </h3>
Aqui o recomendado seria um `h2` já que _formação_ é um subtítulo de _Brunna_ e não de _objetivo_.

2017-03-07 03:23 UTC, edysegura commented on brunna-de-souza/1.ii/index.html
> +<h4> EXPERIÊNCIA PROFISSIONAL </h4>
`h2 `aqui também!

2017-03-07 03:23 UTC, edysegura commented on brunna-de-souza/1.ii/index.html
> +<h5> •	2014-2016(Atual) – Escritorio Contabil Eldorado </h5>
Aqui poderia ser um `h3 `devido _2014-2016(Atual) – Escritorio Contabil Eldorado_ ser um subtítulo de de _experiência profissional_

2017-03-07 03:27 UTC, edysegura commented on exercicio 1 si
> +<!DOCTYPE>
Esse arquivo "exercicio 1 si" você pode remover!

2017-03-09 02:32 UTC, edysegura requested changes
Olá @Brunna10 !

Primeiramente parabéns pelo seu dia!! Ainda há correções que precisamos fazer no seu exercícios. Vamos fazer juntos na aula amanhã.

Abraços,

2017-03-09 12:15 UTC, Brunna10 commented
Muito Obrigada @edysegura  pela lembrança, ok.

2017-03-22 01:37 UTC, edysegura reviewed
Olá @Brunna10 !

Quase lá! Faltou colocar o seu nome no título do documento e formatar o seu HTML para facilitar a leitura e manutenção do mesmo.

Abraços,

2017-03-22 01:37 UTC, edysegura commented on brunna-de-souza/1.ii/index.html
> +        <title>Currículo Vitae </title>
Trocar o currículo vitae para o seu nome!

2017-03-22 16:17 UTC, Brunna10 commented
@edysegura  coloquei meu nome.

2017-03-22 19:41 UTC, edysegura reviewed
Good job!!

2017-03-22 19:41 UTC, edysegura approved these changes

2017-03-22 19:42 UTC, merged